global:
  scrape_interval: 5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'rag-api'
    metrics_path: /metrics
    static_configs:
      - targets: ['rag-api:8081']